name: k6_test

services:
  nginx:
    image: nginx:1.23
    container_name: loadtest_nginx
    ports:
      - mode: ingress
        target: 80
        published: 8080
        protocol: tcp

  grafana:
    image: grafana/grafana
    container_name: loadtest_grafana
    ports:
      - mode: ingress
        target: 3000
        published: 3000
        protocol: tcp
    user: "root"
    depends_on:
      - influxdb
    volumes:
      - type: bind
        source: ./grafana/dashboards
        target: /etc/grafana/provisioning/dashboards
        bind:
          create_host_path: true
      - type: bind
        source: ./grafana/datasources
        target: /etc/grafana/provisioning/datasources
        bind:
          create_host_path: true

  influxdb:
    image: influxdb:1.8
    container_name: loadtest_influxdb
    ports:
      - mode: ingress
        target: 8086
        published: 8086
        protocol: tcp
    environment:
      INFLUXDB_DB: "loadtest"
    volumes:
      - type: bind
        source: ./influxdb/data
        target: /var/lib/influxdb
        bind:
          create_host_path: true
