apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: k6-operator
spec:
  selector:
    app: influxdb
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
