resources:
  - "namespace.yaml"
  - "crds"
  - "clusterrole-manager.yaml"
  - "clusterrole-metrics-reader.yaml"
  - "clusterrole-proxy.yaml"
  - "clusterrolebinding-manager.yaml"
  - "clusterrolebinding-proxy.yaml"
  - "deployment.yaml"
  - "role.yaml"
  - "rolebinding.yaml"
  - "service.yaml"
  - "serviceaccount.yaml"
