apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: playground
      app.kubernetes.io/owner: sre
      app.kubernetes.io/group: monitoring
    includeTemplates: true
namespace: kube-system
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server
    releaseName: metrics-server
    version: 3.12.2
    valuesFile: ./values.yaml
    namespace: kube-system
    includeCRDs: true
