apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-operator-example01
  namespace: k6-operator
spec:
  parallelism: 1
  arguments: -o xk6-influxdb=http://influxdb2.influxdb.svc.cluster.local:80
  script:
    configMap:
      name: k6-operator-example01
      file: load-test.js
  runner:
    image: ren1007/k6:latest
    env:
      - name: K6_INFLUXDB_ORGANIZATION
        value: "loadtest_organization"
      - name: K6_INFLUXDB_BUCKET
        value: "loadtest_result"
      - name: K6_INFLUXDB_TOKEN
        value: "admin_token"
      - name: K6_INFLUXDB_PUSH_INTERVAL
        value: "30s"
    metadata:
      labels: # k6 ワークロード（Sender Pod）に伝搬するラベルを設定
        app.kubernetes.io/owner: sre
        app.kubernetes.io/group: monitoring
        app.kubernetes.io/subgroup: load-testing
        app.kubernetes.io/name: k6
        app.kubernetes.io/managed-by: cli
    resources:
      requests:
        memory: "5Gi"
        cpu: "2"
      limits:
        memory: "10Gi"
        cpu: "4"
