apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-operator-example01
  namespace: k6-operator
spec:
  parallelism: 1
  arguments: -o experimental-prometheus-rw
  script:
    configMap:
      name: k6-operator-example01
      file: load-test.js
  runner:
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
    metadata:
      labels: # k6 ワークロード（Sender Pod）に伝搬するラベルを設定
        app.kubernetes.io/owner: sre
        app.kubernetes.io/group: monitoring
        app.kubernetes.io/subgroup: load-testing
        app.kubernetes.io/name: k6
        app.kubernetes.io/managed-by: cli
