apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb.local:8086
    isDefault: true
    secureJsonData:
      token: admin_token
    jsonData:
      version: Flux
      organization: loadtest_organization
      defaultBucket: loadtest_result
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.local:9090
    orgId: 1
    editable: true
